spring.application.name=mondial-backend

spring.datasource.url=jdbc:h2:mem:mondialdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.h2.console.enabled=true

app.jwt.secret=replace-this-with-a-very-long-secret-key-32-bytes-minimum
app.jwt.expiration-ms=86400000

