spring.application.name=mondial-backend

spring.datasource.url=${DB_URL:jdbc:postgresql://ep-long-breeze-amljbz2n.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${DB_USER:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_ZBlEnVDi8WJ6}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

app.jwt.secret=${APP_JWT_SECRET:replace-this-with-a-very-long-secret-key-32-bytes-minimum}
app.jwt.expiration-ms=86400000

google.client-id=${GOOGLE_CLIENT_ID:764101679968-ba91lkrh8gk92693v9c67tuqiium71lj.apps.googleusercontent.com}

wc2026.api.base-url=https://api.wc2026api.com
wc2026.api.key=${WC2026_API_KEY:wc26_YW697WMUDWfFJuc5iiLUPY}

